#F82ebvCI-ch-setup-testing-environment with-jest-and-enzyme ,and Travis -Ci
atlp-rwanda/eagles-phantom-frontend pull request #2
Opened 2020-11-13 05:39 UTC by Mugema123

**What does this PR do?**
`Setup testing environment with jest and enzyme`
`Travis CI is configured as a continuous integration service used to build and test the app.`
**Description of Task to be completed?**
`Configured Testing environment with Jest & Enzyme to ensure that all functionalities are tested before deployment.`
`Travis CI is configured as a continuous integration service used to build and test the app.`
`Travis CI badge has been added to your repo`
`Configure CodeClimate for code analysis and Maintainability checking.`

**How should this be manually tested?**
`Clone the repo locally`
`run npm i`
`run npm test`

**What are the relevant pivotal tracker stories?**
#F82ebvCI
**Screenshots (if appropriate)**
<img width="960" alt="m1" src="https://user-images.githubusercontent.com/68016181/99033122-33817e00-2583-11eb-985c-68bc4c30ec7d.png">
<img width="960" alt="m2" src="https://user-images.githubusercontent.com/68016181/99033232-3d0ae600-2583-11eb-8330-67692a688f56.png">

2020-11-13 10:07 UTC, Ntwali-Josue reviewed
try to not push node_modules and .vscode folders

2020-11-13 10:47 UTC, Ntwali-Josue approved these changes, later dismissed

2020-11-13 10:50 UTC, Ntwali-Josue commented on .vscode/settings.json
> +}
please add this vscode file in your gitignore

2020-11-13 10:50 UTC, Ntwali-Josue commented on .babelrc
> +
At the end of each file of yours add a single empty line.

2020-11-13 11:08 UTC, Ally4 approved these changes, later dismissed

2020-11-13 12:20 UTC, TuyizeeAnastase reviewed
can you use first letter capitalized
 for components.

2020-11-13 13:12 UTC, TuyizeeAnastase submitted a review, later dismissed

2020-11-13 13:13 UTC, Ally4 approved these changes, later dismissed

2020-11-14 08:58 UTC, Ntwali-Josue submitted a review, later dismissed

2020-11-16 11:32 UTC, ceelogre reviewed
Look at the comments and rebase so we can proceed.

2020-11-16 11:32 UTC, ceelogre commented on package.json
> +    "@webpack-cli/init": "^1.0.3",
Do we really need to have these in dependencies?

2020-11-16 11:32 UTC, ceelogre commented on package.json
> +    "runtime": "^0.14.1",
What's the use of this package?

2020-11-16 11:32 UTC, ceelogre commented on src/App.test.js
> +
There's no 'initial message' tested here.

2020-11-17 05:08 UTC, Ntwali-Josue submitted a review, later dismissed

2020-11-18 11:40 UTC, TuyizeeAnastase approved these changes, later dismissed

2020-11-18 11:45 UTC, Ally4 commented
Hi Ronald, First change the label on this PR, and work on the coverage, and change the screenshot in the PR, otherwise it a good job

2020-11-18 11:50 UTC, Ally4 commented
give also the badges their own field, not in the installation field

2020-11-18 12:04 UTC, Ally4 commented
give also the badges their own field, not in the installation field

2020-11-18 12:27 UTC, Ntwali-Josue requested changes

2020-11-18 12:27 UTC, Ntwali-Josue commented on coverage/lcov-report/index.html
> +        <script>
don't push coverage

2020-11-18 12:27 UTC, Ntwali-Josue commented on coverage/lcov-report/sorter.js
> +        rows.sort(finalSorter);
remove these coverage files

2020-11-18 14:00 UTC, Ntwali-Josue submitted a review, later dismissed

2020-11-18 14:05 UTC, TuyizeeAnastase approved these changes, later dismissed

2020-11-18 14:09 UTC, Ally4 submitted a review, later dismissed

2020-11-18 14:23 UTC, Ntwali-Josue approved these changes

2020-11-18 14:23 UTC, ceelogre approved these changes

2020-11-18 14:23 UTC, merged