#6yTQ5Oqv Landing Page
atlp-rwanda/eagles-phantom-frontend pull request #4
Opened 2020-11-16 15:54 UTC by TuyizeeAnastase

### What does this PR do?
-building landing page or homepage of phantom project

### description of tasks to be completed
-implementing landing page
-landing page is responsive
-page has important links and app info
-Skelton screen when app is loading

### How can be manually tested?
-clone this repo
-run `npm install `
-run `npm run start`
-see the opened link in your default browser

### Relavant trello story
[](https://trello.com/c/6yTQ5Oqv/28-landing-page)

2020-12-12 07:42 UTC, Mugema123 approved these changes

2020-12-12 07:45 UTC, Ntwali-Josue requested changes

2020-12-12 07:45 UTC, Ntwali-Josue commented on src/components/landingPage/ShortAbt.js
> +// <h2>The following is the counter of number.</h2>
remove the comments

2020-12-12 07:45 UTC, Ntwali-Josue commented on src/index.js
> +debugger;
I think you need to remove this line 8, you still don't need it.

2020-12-12 09:38 UTC, Ally4 approved these changes

2020-12-22 13:06 UTC, Ntwali-Josue approved these changes

2020-12-27 19:22 UTC, ceelogre approved these changes

2020-12-27 19:22 UTC, merged